# Generated by Django 5.1.15 on 2026-08-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_education_start_end_date_no_key_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
