# Generated by Django 5.1.15 on 2026-07-26 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CVDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("html_source", models.TextField()),
                ("pdf_file", models.FileField(upload_to="cv_documents/")),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generation_type",
                    models.CharField(
                        choices=[("automatic", "Automatica"), ("manual", "Manuale")],
                        max_length=10,
                    ),
                ),
                ("enrichment_used", models.TextField(blank=True, default="")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_documents",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
