# Generated by Django 5.1.15 on 2026-08-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='areas_of_expertise_grounding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
