# Generated by Django 5.1.15 on 2026-07-26 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="user",
            name="cv_include_photo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="cv_language_mode",
            field=models.CharField(
                choices=[
                    ("english", "English"),
                    ("job_language", "Lingua dell'offerta"),
                ],
                default="job_language",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="extra_credit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="user",
            name="interface_language",
            field=models.CharField(
                choices=[("it", "Italiano"), ("en", "English")],
                default="it",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_activity_reset",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="objective_statement",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="plan",
            field=models.CharField(
                choices=[("free", "Free"), ("pro", "Pro")],
                default="free",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(default="Europe/Rome", max_length=50),
        ),
    ]
