# Generated by Django 5.1.15 on 2026-07-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_inactivity_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
