# Generated by Django 5.1.15 on 2026-07-26 16:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("linkedin", "LinkedIn")],
                        default="linkedin",
                        max_length=20,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("apply_url", models.URLField(max_length=1000)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("salary", models.CharField(blank=True, default="", max_length=255)),
                (
                    "origin",
                    models.CharField(
                        choices=[("collected", "Raccolto"), ("imported", "Importato")],
                        default="collected",
                        max_length=20,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nuovo"),
                            ("cv_generated", "CV generato"),
                            ("application_done", "Candidatura fatta"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("cv_generation_in_progress", models.BooleanField(default=False)),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("score_match", models.JSONField(blank=True, default=list)),
                ("score_gaps", models.JSONField(blank=True, default=list)),
                ("score_reasoning", models.TextField(blank=True, default="")),
                ("date_collected", models.DateTimeField(auto_now_add=True)),
                ("date_scored", models.DateTimeField(blank=True, null=True)),
                ("date_cv_generated", models.DateTimeField(blank=True, null=True)),
                ("date_application_done", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("collection", "Raccolta"),
                            ("scoring", "Scoring"),
                            ("cv_generation", "Generazione CV"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Successo"), ("failure", "Fallimento")],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="run_logs",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="run_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("manual_cv_count", models.PositiveIntegerField(default=0)),
                ("import_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_quotas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="unique_daily_quota_per_user_date"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                fields=("user", "source", "external_id"),
                name="unique_job_per_user_source_external_id",
            ),
        ),
    ]
