# Generated by Django 5.1.15 on 2026-07-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="discarded_by_cap",
            field=models.BooleanField(default=False),
        ),
    ]
