# Generated by Django 5.1.15 on 2026-07-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_schedule_nightly_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='matched_search',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
